disableKinds:
- taxonomyTerm
- taxonomy
- 404
- RSS
- sitemap

baseURL: https://brixy.github.io/hugo-multilanguage-test/
publishDir: docs
languages:
  en:
    languageName: English
    weight: 1
  fr:
    languageName: Français
    weight: 2
  es:
    languageName: Spanish
    weight: 3
